import type {
  AspectSpec,
  Preset,
  PresetCategory,
  ProviderId,
  ProviderModel,
} from './types'

// ---- Providers + models ------------------------------------------------------
export const MODELS: Record<string, ProviderModel> = {
  'flux-schnell': { id: 'flux-schnell', provider: 'fal', label: 'FLUX schnell' },
  'flux-dev': { id: 'flux-dev', provider: 'fal', label: 'FLUX dev' },
  'firefly-v3': { id: 'firefly-v3', provider: 'adobe', label: 'Firefly v3' },
  'sd-turbo': { id: 'sd-turbo', provider: 'ondevice', label: 'SD-Turbo · WebGPU' },
}

export const PROVIDER_ORDER: ProviderId[] = ['fal', 'adobe', 'ondevice']

// ---- Aspect ratios -----------------------------------------------------------
export const ASPECTS: AspectSpec[] = [
  {
    id: 'square',
    label: 'Carré',
    ratio: '1:1',
    width: 1024,
    height: 1024,
    falSize: 'square_hd',
    firefly: { width: 1024, height: 1024 },
  },
  {
    id: 'portrait',
    label: 'Portrait',
    ratio: '4:5',
    width: 896,
    height: 1120,
    falSize: 'portrait_4_3',
    firefly: { width: 896, height: 1120 },
  },
  {
    id: 'tall',
    label: 'Vertical',
    ratio: '9:16',
    width: 768,
    height: 1344,
    falSize: 'portrait_16_9',
    firefly: { width: 768, height: 1344 },
  },
  {
    id: 'landscape',
    label: 'Paysage',
    ratio: '4:3',
    width: 1152,
    height: 896,
    falSize: 'landscape_4_3',
    firefly: { width: 1152, height: 896 },
  },
  {
    id: 'wide',
    label: 'Scope',
    ratio: '16:9',
    width: 1344,
    height: 768,
    falSize: 'landscape_16_9',
    firefly: { width: 1344, height: 768 },
  },
]

export const aspectById = (id: string): AspectSpec =>
  ASPECTS.find((a) => a.id === id) ?? ASPECTS[0]

// ---- Categories --------------------------------------------------------------
export interface CategoryMeta {
  id: PresetCategory
  nameFr: string
  nameEn: string
  taglineFr: string
  taglineEn: string
  color: string // tailwind cat.* hex
}

export const CATEGORIES: CategoryMeta[] = [
  {
    id: 'pellicule',
    nameFr: 'Pellicule',
    nameEn: 'Film stock',
    taglineFr: 'Le grain, la couleur, la chimie',
    taglineEn: 'Grain, colour, chemistry',
    color: '#e0563b',
  },
  {
    id: 'eclairage',
    nameFr: 'Éclairage',
    nameEn: 'Lighting',
    taglineFr: 'D’où vient la lumière',
    taglineEn: 'Where the light comes from',
    color: '#f4a522',
  },
  {
    id: 'affiche',
    nameFr: 'Affiche',
    nameEn: 'Poster',
    taglineFr: 'Graphisme, sérigraphie, époque',
    taglineEn: 'Graphic design, print, era',
    color: '#d23b6e',
  },
  {
    id: 'medium',
    nameFr: 'Médium',
    nameEn: 'Medium',
    taglineFr: 'À la main : peinture, gravure, pâte',
    taglineEn: 'By hand: paint, print, clay',
    color: '#1b9c7a',
  },
  {
    id: 'docphoto',
    nameFr: 'Doc / Photo',
    nameEn: 'Doc / Photo',
    taglineFr: 'Reportage, grand format, instantané',
    taglineEn: 'Reportage, large format, instant',
    color: '#5a86c4',
  },
]

export const categoryById = (id: PresetCategory): CategoryMeta =>
  CATEGORIES.find((c) => c.id === id) ?? CATEGORIES[0]

// ---- The preset catalog (the signature) --------------------------------------
// Each preset = an English prompt fragment + optional negative + native aspect.
const P = (
  id: string,
  category: PresetCategory,
  nameFr: string,
  nameEn: string,
  blurbFr: string,
  blurbEn: string,
  fragment: string,
  swatch: [string, string],
  extra?: { negative?: string; aspect?: Preset['aspect'] },
): Preset => ({
  id,
  category,
  nameFr,
  nameEn,
  blurbFr,
  blurbEn,
  fragment,
  swatch,
  ...extra,
})

export const PRESETS: Preset[] = [
  // ---------------- PELLICULE ----------------
  P('portra-400', 'pellicule', 'Portra 400', 'Portra 400',
    'Tons chair crémeux, basse saturation', 'Creamy skin, low saturation',
    'shot on Kodak Portra 400, soft pastel colour palette, creamy natural skin tones, gentle fine grain, low contrast, photographed on medium format film',
    ['#e8c9a8', '#b98c63'], { aspect: 'portrait' }),
  P('tri-x', 'pellicule', 'Tri-X 400', 'Tri-X 400',
    'Noir et blanc nerveux, grain marqué', 'Gritty black & white, heavy grain',
    'shot on Kodak Tri-X 400 black and white film, high contrast, pronounced silver grain, deep blacks, documentary monochrome',
    ['#1a1a1a', '#cfcfcf'], { aspect: 'square' }),
  P('ektachrome', 'pellicule', 'Ektachrome', 'Ektachrome',
    'Diapo froide, bleus éclatants', 'Cool slide film, vivid blues',
    'shot on Kodak Ektachrome slide film, cool colour cast, vivid saturated blues, crisp clarity, fine grain, vintage editorial look',
    ['#2e6f8e', '#d8e6ec']),
  P('cinestill-800t', 'pellicule', 'CineStill 800T', 'CineStill 800T',
    'Néons nocturnes, halations rouges', 'Night neon, red halation',
    'shot on CineStill 800T tungsten film, night photography, glowing red halation around highlights, cyan shadows, cinematic grain',
    ['#0c1a2a', '#ff5a4d'], { aspect: 'wide' }),
  P('velvia-50', 'pellicule', 'Velvia 50', 'Velvia 50',
    'Couleurs survitaminées, paysage', 'Hyper-saturated, landscape',
    'shot on Fujifilm Velvia 50, ultra-saturated landscape colours, punchy greens and reds, extreme sharpness, slide film clarity',
    ['#0f7a3d', '#e0431f'], { aspect: 'wide' }),
  P('hp5', 'pellicule', 'Ilford HP5', 'Ilford HP5',
    'N&B classique, gris doux', 'Classic B&W, soft grays',
    'shot on Ilford HP5 Plus black and white film, classic mid-tone rich grayscale, organic grain, timeless reportage monochrome',
    ['#2b2b2b', '#bdbdbd']),
  P('gold-200', 'pellicule', 'Kodak Gold 200', 'Kodak Gold 200',
    'Été nostalgique, ambre chaud', 'Nostalgic summer, warm amber',
    'shot on Kodak Gold 200, warm golden amber cast, nostalgic 90s consumer film look, soft grain, sunny snapshot feel',
    ['#e0a93b', '#c46a2a']),
  P('lomo-purple', 'pellicule', 'Lomo Purple', 'Lomo Purple',
    'Virage onirique mauve-lime', 'Dreamy purple-lime shift',
    'shot on LomoChrome Purple film, surreal colour shift turning greens to lavender and purple, dreamlike infrared palette, heavy grain',
    ['#7b4ea0', '#b9d36b']),
  P('expired-film', 'pellicule', 'Pellicule expirée', 'Expired film',
    'Couleurs déviées, fuites de lumière', 'Shifted colours, light leaks',
    'shot on expired colour film, unpredictable colour shifts, light leaks, faded muddy tones, analogue imperfection, dusty texture',
    ['#9a7b53', '#d65a3a']),

  // ---------------- ÉCLAIRAGE ----------------
  P('rembrandt', 'eclairage', 'Rembrandt', 'Rembrandt',
    'Triangle de lumière, ombres riches', 'Light triangle, rich shadows',
    'Rembrandt lighting, dramatic single key light, characteristic triangle of light on the shadowed cheek, deep chiaroscuro shadows, painterly',
    ['#2a1d10', '#e0a94a'], { aspect: 'portrait' }),
  P('golden-hour', 'eclairage', 'Heure dorée', 'Golden hour',
    'Soleil rasant, contre-jour chaud', 'Low sun, warm backlight',
    'golden hour lighting, warm low-angle sun, long soft shadows, glowing rim light, hazy backlit atmosphere, honeyed warmth',
    ['#f0a93b', '#d6622a'], { aspect: 'wide' }),
  P('neon-nuit', 'eclairage', 'Néon nuit', 'Neon night',
    'Magenta/cyan, ville pluvieuse', 'Magenta/cyan, rainy city',
    'neon night lighting, magenta and cyan colour wash, wet reflective streets, glowing signage, moody cyberpunk urban atmosphere',
    ['#d23b6e', '#2bb0c4'], { aspect: 'wide' }),
  P('clair-obscur', 'eclairage', 'Clair-obscur', 'Chiaroscuro',
    'Noir profond, lumière unique', 'Deep black, single light',
    'extreme chiaroscuro, single dramatic light source, near-black surroundings, sculptural highlights, baroque tenebrism, intense contrast',
    ['#0a0a0a', '#e8d9b0'], { negative: 'flat lighting, evenly lit' }),
  P('softbox-studio', 'eclairage', 'Softbox studio', 'Softbox studio',
    'Lumière douce, fond uni', 'Soft even light, plain seamless',
    'clean studio lighting, large softbox key light, even soft shadows, seamless backdrop, commercial product-grade clarity, crisp',
    ['#e8e6e0', '#9c9a94'], { aspect: 'square' }),
  P('split-light', 'eclairage', 'Lumière latérale', 'Split light',
    'Moitié éclairée, moitié dans l’ombre', 'Half lit, half in shadow',
    'split lighting, side key light illuminating exactly half the face, the other half in deep shadow, tense dramatic mood',
    ['#1c1c22', '#cfae6e'], { aspect: 'portrait' }),
  P('overcast', 'eclairage', 'Ciel couvert', 'Overcast',
    'Lumière diffuse, ombres douces', 'Diffuse light, soft shadows',
    'soft overcast daylight, fully diffused even illumination, gentle shadows, muted desaturated palette, calm naturalistic mood',
    ['#b8bcc0', '#7c8086']),
  P('hard-noir', 'eclairage', 'Film noir', 'Film noir',
    'Stores, ombres tranchées', 'Venetian blinds, hard shadows',
    'classic film noir lighting, hard directional light through venetian blinds casting bold striped shadows, high contrast black and white mood',
    ['#0d0d0d', '#d9d4c4'], { aspect: 'landscape' }),
  P('bioluminescent', 'eclairage', 'Bioluminescence', 'Bioluminescent',
    'Lueur froide venue d’en bas', 'Cold glow from within',
    'eerie bioluminescent lighting, cold cyan and green glow emanating from below, otherworldly underlit subject, dark surroundings',
    ['#0a3a3a', '#3effc4']),
  P('candlelight', 'eclairage', 'Chandelle', 'Candlelight',
    'Flamme chaude, falloff rapide', 'Warm flame, fast falloff',
    'intimate candlelight, single warm flickering flame, rapid light falloff into darkness, amber glow on faces, La Tour painterly intimacy',
    ['#3a1f0a', '#f0b25a'], { aspect: 'portrait' }),

  // ---------------- AFFICHE ----------------
  P('saul-bass', 'affiche', 'Saul Bass', 'Saul Bass',
    'Formes découpées, aplats audacieux', 'Cut shapes, bold flats',
    'Saul Bass poster style, bold cut-paper shapes, flat limited colour palette, dramatic negative space, graphic mid-century title-sequence design',
    ['#e0431f', '#1a1a1a'], { negative: 'photographic, realistic shading', aspect: 'portrait' }),
  P('bauhaus', 'affiche', 'Bauhaus', 'Bauhaus',
    'Géométrie primaire, grille stricte', 'Primary geometry, strict grid',
    'Bauhaus design, primary colour geometric shapes, strict modernist grid, clean sans-serif forms, red yellow blue and black, constructivist',
    ['#d6242a', '#f0c419'], { negative: 'photographic, gradients', aspect: 'portrait' }),
  P('riso', 'affiche', 'Risographie', 'Risograph',
    'Trames, surimpressions fluo', 'Halftone, fluoro overprint',
    'risograph print look, two-colour fluorescent ink overprint, visible halftone dot texture, slight misregistration, grainy paper, DIY zine aesthetic',
    ['#ff48b0', '#3effc4'], { aspect: 'portrait' }),
  P('sci-fi-70s', 'affiche', 'Sci-fi 70s', '70s sci-fi',
    'Aérographe, dégradés cosmiques', 'Airbrush, cosmic gradients',
    '1970s science fiction paperback cover art, airbrushed cosmic gradients, chrome lettering vibe, retro-futurist palette, lens flares, pulp grandeur',
    ['#5b2a8c', '#f0903b'], { aspect: 'portrait' }),
  P('criterion', 'affiche', 'Criterion', 'Criterion',
    'Art-house épuré, typo soignée', 'Art-house restraint, fine type',
    'Criterion Collection cover aesthetic, restrained art-house composition, elegant minimal layout, refined muted palette, tasteful negative space',
    ['#1c2a3a', '#d8c7a0'], { aspect: 'portrait' }),
  P('constructivist', 'affiche', 'Constructivisme', 'Constructivist',
    'Diagonales rouges, photomontage', 'Red diagonals, photomontage',
    'Russian constructivist poster, bold red and black diagonal composition, dynamic photomontage, heavy geometric sans-serif, propaganda energy',
    ['#c81d1d', '#111111'], { aspect: 'portrait' }),
  P('art-deco', 'affiche', 'Art déco', 'Art deco',
    'Symétrie dorée, lignes fines', 'Gilded symmetry, fine lines',
    'Art Deco poster, symmetrical geometric ornament, gold and deep teal palette, elegant streamlined linework, 1920s luxury travel-poster grandeur',
    ['#c79a3b', '#0f5a52'], { aspect: 'portrait' }),
  P('grindhouse', 'affiche', 'Grindhouse', 'Grindhouse',
    'Usé, taché, exploitation 70s', 'Worn, stained, 70s exploitation',
    'grindhouse exploitation poster, distressed scratched texture, lurid high-contrast colour, faux-worn print, sensational 1970s B-movie energy',
    ['#a61b1b', '#e0a32a'], { aspect: 'portrait' }),
  P('swiss-grid', 'affiche', 'Style suisse', 'Swiss style',
    'Helvetica, grille rigoureuse', 'Helvetica, rigorous grid',
    'Swiss International Typographic Style, rigorous grid, generous white space, Helvetica clarity, asymmetric balance, objective restrained design',
    ['#e0e0e0', '#d6242a'], { negative: 'ornate, decorative, photographic clutter', aspect: 'portrait' }),

  // ---------------- MÉDIUM ----------------
  P('aquarelle', 'medium', 'Aquarelle', 'Watercolour',
    'Lavis fluide, bords mouillés', 'Fluid washes, wet edges',
    'delicate watercolour painting, translucent flowing washes, soft wet-on-wet bleeding edges, visible paper texture, luminous pigment pooling',
    ['#6aa0d6', '#e08a9c'], { negative: 'photographic, 3d render' }),
  P('gravure', 'medium', 'Gravure', 'Engraving',
    'Hachures fines, taille-douce', 'Fine hatching, intaglio',
    'fine copperplate engraving, dense cross-hatching, intricate intaglio line work, monochrome ink on cream paper, antique illustration precision',
    ['#2b2b2b', '#e8e0cc'], { negative: 'colour, soft gradients, photographic', aspect: 'portrait' }),
  P('fusain', 'medium', 'Fusain', 'Charcoal',
    'Traits gras, estompes', 'Bold strokes, smudges',
    'expressive charcoal drawing, bold smudged strokes, rich black and gray tonal range, visible paper grain, gestural life-drawing energy',
    ['#1c1c1c', '#bdb8ad'], { negative: 'colour, photographic, crisp digital' }),
  P('gouache', 'medium', 'Gouache', 'Gouache',
    'Aplats mats, couleur opaque', 'Matte flats, opaque colour',
    'gouache painting, opaque matte flat colour areas, visible brushwork, slightly chalky pigment, mid-century illustration warmth',
    ['#e0795a', '#3b7a8c']),
  P('clay-3d', 'medium', 'Pâte 3D', '3D clay',
    'Personnages en pâte, stop-motion', 'Clay characters, stop-motion',
    'handmade clay stop-motion look, soft sculpted plasticine forms, visible fingerprints and tool marks, charming tactile claymation, soft studio light',
    ['#e0a35a', '#6a9a6a']),
  P('lino', 'medium', 'Linogravure', 'Linocut',
    'Aplats noirs, gouge visible', 'Black flats, carved marks',
    'bold linocut print, thick carved black ink shapes, visible gouge texture, high-contrast hand-printed relief, rough organic edges, limited colour',
    ['#161616', '#e8e2d0'], { negative: 'smooth gradients, photographic' }),
  P('oil-impasto', 'medium', 'Huile impasto', 'Oil impasto',
    'Empâtement épais, matière', 'Thick paint, texture',
    'thick impasto oil painting, heavy sculptural brushstrokes, palette-knife texture, rich layered pigment catching light, expressive painterly surface',
    ['#7a4a2a', '#d6b35a']),
  P('ukiyo-e', 'medium', 'Ukiyo-e', 'Ukiyo-e',
    'Estampe japonaise, contours nets', 'Japanese woodblock, clean lines',
    'Japanese ukiyo-e woodblock print, flat clean outlines, limited natural pigment palette, decorative flowing composition, wave and cloud motifs',
    ['#1f5a7a', '#e0c08a'], { aspect: 'portrait' }),
  P('cyanotype', 'medium', 'Cyanotype', 'Cyanotype',
    'Bleu de Prusse, contact', 'Prussian blue, contact print',
    'cyanotype contact print, deep Prussian blue monochrome, white silhouetted forms, soft photographic edges, antique botanical-print feel',
    ['#0d3b6e', '#dce8f0']),

  // ---------------- DOC / PHOTO ----------------
  P('reportage-nb', 'docphoto', 'Reportage N&B', 'B&W reportage',
    'Photojournalisme, instant décisif', 'Photojournalism, decisive moment',
    'black and white photojournalism, candid decisive-moment composition, available light, 35mm reportage grain, gritty documentary authenticity',
    ['#202020', '#c0c0c0'], { aspect: 'landscape' }),
  P('large-format', 'docphoto', 'Grand format', 'Large format',
    'Portrait 8x10, détail extrême', '8x10 portrait, extreme detail',
    'large format 8x10 view camera portrait, razor-sharp tonal detail, shallow depth of field, formal studio portrait, exquisite skin texture rendering',
    ['#3a342c', '#d8cbb0'], { aspect: 'portrait' }),
  P('polaroid', 'docphoto', 'Polaroïd', 'Polaroid',
    'Instantané, cadre blanc, virage', 'Instant, white frame, shift',
    'vintage Polaroid SX-70 instant photo, soft faded colours, slight green-yellow cast, gentle vignette, square white border, nostalgic snapshot',
    ['#cbb98f', '#7a9a7a'], { aspect: 'square' }),
  P('tilt-shift', 'docphoto', 'Tilt-shift', 'Tilt-shift',
    'Effet miniature, flou sélectif', 'Miniature effect, selective blur',
    'tilt-shift photography, miniature-faking selective focus, sharp central band with strong top and bottom blur, saturated toy-like colours, aerial view',
    ['#5a9a6a', '#d6a33b'], { aspect: 'wide' }),
  P('infrared', 'docphoto', 'Infrarouge', 'Infrared',
    'Feuillage blanc, ciels sombres', 'White foliage, dark skies',
    'infrared photography, glowing white foliage, dramatically darkened skies, surreal false-colour tonal inversion, dreamlike otherworldly landscape',
    ['#e8e0e8', '#3a2a4a'], { aspect: 'landscape' }),
  P('drone-topdown', 'docphoto', 'Vue drone', 'Drone top-down',
    'Plan zénithal, motifs au sol', 'Top-down, ground patterns',
    'top-down aerial drone photograph, perfect bird’s-eye perspective, strong graphic ground patterns, long shadows, geometric abstraction of landscape',
    ['#7a6a4a', '#3a6a8a'], { aspect: 'square' }),
  P('macro', 'docphoto', 'Macro', 'Macro',
    'Très gros plan, bokeh crémeux', 'Extreme close-up, creamy bokeh',
    'extreme macro photography, razor-thin depth of field, intricate fine texture detail, creamy out-of-focus bokeh background, dewy luminous close-up',
    ['#3a7a5a', '#d6a3b3'], { aspect: 'square' }),
  P('flash-direct', 'docphoto', 'Flash direct', 'Direct flash',
    'Flash cru, ombres dures', 'Harsh flash, hard shadows',
    'direct on-camera flash photography, harsh frontal light, hard dark drop shadows, slightly overexposed subject, raw candid party-snapshot energy',
    ['#e8e2d0', '#1c1c1c']),
]

export const presetById = (id: string): Preset | undefined =>
  PRESETS.find((p) => p.id === id)

export const presetsByCategory = (cat: PresetCategory): Preset[] =>
  PRESETS.filter((p) => p.category === cat)
